services:
  nuxt-daisyui-website-preview:
    container_name: template-website-website
    build:
      context: .
      target: production-stage
    ports:
      - '127.0.0.1:3001:3001'
    networks:
      - app-network # Connect to the shared network

networks:
  app-network:
    external: true # Use the external network created earlier
